#!/bin/bash
# Quick reference for Gemini-only Personal Research Analyst

echo "=========================================="
echo "PERSONAL RESEARCH ANALYST - QUICK REFERENCE"
echo "=========================================="
echo ""
echo "📋 CHECKLIST:"
echo ""
echo "  [ ] Get Gemini API key from https://aistudio.google.com/apikey"
echo "  [ ] Edit .env: GOOGLE_API_KEY=your-key"
echo "  [ ] Terminal 1: python -m src.llm_gatewayV3.main"
echo "  [ ] Terminal 2: python -m src.agent6"
echo ""
echo "🔧 SETUP COMMANDS:"
echo ""
echo "  source .venv/bin/activate"
echo "  pip install -e ."
echo "  python -m pytest tests/test_layers.py -v"
echo ""
echo "📂 KEY FILES:"
echo ""
echo "  .env                    → Your API key (DO NOT commit)"
echo "  gemini_config.py        → Configuration reference"
echo "  GEMINI_SETUP.md         → Full setup guide"
echo "  tests/test_layers.py    → Unit tests"
echo ""
echo "🚀 ARCHITECTURE:"
echo ""
echo "  User Query"
echo "    ↓"
echo "  Perception (intent analysis)"
echo "    ↓"
echo "  Decision (choose next action)"
echo "    ↓"
echo "  Action (search_web, crawl_url, finish)"
echo "    ↓"
echo "  Gemini API (via llm_gatewayV3)"
echo ""
echo "✓ All code fixed"
echo "✓ Duplicate imports removed"
echo "✓ Unit tests created"
echo "✓ Gemini-only configured"
echo ""
